---
meta:
    app: backhaul
    version: alpha

logging:
    logfile: backhaul.log

graphics:
    resolution: 1366x768
    fullscreen: True

assets:
    - assets
    - assets/tiles
tileHeight: 27
tileWidth: 62