---
logging:
  logfile: backhaul.log
  loglvl: debug

graphics:
  resolution: 1920x1080
  fullscreen: false
  chunk:
    radius: 10

assets:
  base: /home/tmac/projects/public/backhaul/assets
  tiles: tiles/
  fonts: fonts/
  ui: ui/

tile:
  width: 32
  height: 16

data:
  saved_games: /home/tmac/projects/public/backhaul/saves